package view;

/**
 *
 * @author HP
 */
public class MainLayout extends javax.swing.JFrame {

    /**
     * Creates new form MainLayout
     */
    public MainLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaText = new javax.swing.JLabel();
        nimText = new javax.swing.JLabel();
        tanggalText = new javax.swing.JLabel();
        statusText = new javax.swing.JLabel();
        showNama = new javax.swing.JTextField();
        showNim = new javax.swing.JTextField();
        showTanggal = new javax.swing.JTextField();
        showStatus = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenuItem();
        ruanganMenu = new javax.swing.JMenu();
        peminjamanMenu = new javax.swing.JMenuItem();
        pengelolaanMenu = new javax.swing.JMenuItem();
        rekapMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Peminjaman Ruangan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 230));
        setMinimumSize(new java.awt.Dimension(750, 230));
        setName("mainLayout"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 230));

        namaText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaText.setText("Nama :");

        nimText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nimText.setText("NIM : ");

        tanggalText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanggalText.setText("Status  : ");

        statusText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusText.setText("Tanggal :");

        showNama.setMaximumSize(new java.awt.Dimension(7, 19));

        showNim.setMaximumSize(new java.awt.Dimension(7, 19));

        showTanggal.setMaximumSize(new java.awt.Dimension(7, 19));

        showStatus.setToolTipText("");
        showStatus.setMaximumSize(new java.awt.Dimension(7, 19));

        menuDashboard.setText("Akun");

        loginMenu.setText("Login");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        menuDashboard.add(loginMenu);

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        menuDashboard.add(logoutMenu);

        menuBar.add(menuDashboard);

        ruanganMenu.setText("Ruangan");

        peminjamanMenu.setText("Peminjaman");
        peminjamanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanMenuActionPerformed(evt);
            }
        });
        ruanganMenu.add(peminjamanMenu);

        pengelolaanMenu.setText("Pengelolaan");
        pengelolaanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengelolaanMenuActionPerformed(evt);
            }
        });
        ruanganMenu.add(pengelolaanMenu);

        rekapMenu.setText("Rekap");
        rekapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapMenuActionPerformed(evt);
            }
        });
        ruanganMenu.add(rekapMenu);

        menuBar.add(ruanganMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showNama, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nimText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showNim, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tanggalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusText)
                        .addComponent(tanggalText)
                        .addComponent(showTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaText)
                        .addComponent(nimText)
                        .addComponent(showNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPengelolaanVisibility(Boolean nilai){
        pengelolaanMenu.setEnabled(nilai);
    }

    private void rekapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekapMenuActionPerformed

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMenuActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    } 

    private void peminjamanMenuActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }   

    private void pengelolaanMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem loginMenu;
    public javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JLabel namaText;
    private javax.swing.JLabel nimText;
    public javax.swing.JMenuItem peminjamanMenu;
    public javax.swing.JMenuItem pengelolaanMenu;
    public javax.swing.JMenuItem rekapMenu;
    public javax.swing.JMenu ruanganMenu;
    private javax.swing.JTextField showNama;
    private javax.swing.JTextField showNim;
    private javax.swing.JTextField showStatus;
    private javax.swing.JTextField showTanggal;
    private javax.swing.JLabel statusText;
    private javax.swing.JLabel tanggalText;
    // End of variables declaration//GEN-END:variables
}
